// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sviulzvoiumtmqkaypoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aXVsenZvaXVtdG1xa2F5cG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTIwOTEsImV4cCI6MjA2NjM2ODA5MX0.eSxTDkTsou8n581-zduHtryTbIIkjOHwUZZP8k58NQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);